# Python 2 + 3 Training Config
# With special tokens added to tokenizer: [python2], [python3]

# Model settings
model_name: "allenai/OLMo-2-0425-1B"

# Global settings
output_dir: /mnt/nvme3/dipika/olmo-code-sft/outputs/models/py2_py3_special_tokens
seed: 42

# Weights & Biases settings
wandb:
  project: "olmo-code-sft"
  entity: null  # Set to your wandb username if needed
  name: "py2_py3_special_tokens"
  tags: ["python2", "python3", "special_tokens"]

# Training settings
# Optimized for 8x H100 80GB GPUs based on profiling

# effective batch size = 4*4*4 = 64. 
training:
  per_device_batch_size: 8  # Increased from 4 to 8
  gradient_accumulation_steps: 4  # Reduced from 8 to 4 (8 × 8 GPUs × 4 = 256 effective batch size)
  num_train_epochs: 5
  max_length: 4096  # Keep this for now
  save_steps: 100
  save_total_limit: 2
  logging_steps: 1
  eval_steps: 100  # Evaluate every 2 steps for testing
  fp16: false
  bf16: true
  optim: "adamw_torch_fused"
  ddp_find_unused_parameters: false
  learning_rate: 4e-6
  warmup_steps: 700
  gradient_checkpointing: true  # Enable gradient checkpointing for memory efficiency

  # Evaluation settings to prevent OOM
  per_device_eval_batch_size: 1  # Much smaller for evaluation
  dataloader_pin_memory: false  # Reduce memory usage
  remove_unused_columns: true  # Clean up unused data
  eval_accumulation_steps: 1  # Reduce accumulation during evaluation

  # 180k per file, 14 "chunks" --> 2M samples. samples per step 4*8 * 8 = 256. 
  # 2M / 256 = 7812.5 steps.  
  # we want warmup ratio to be .1/ or .05 with respect to the total training  steps = 7812.5 steps. * 5 epochs. 
  # 7812.5 * .05 = 390.625 steps. 
  # 7812.5 * .1 = 781.25 steps. 
  # 7812.5 * .2 = 1562.5 steps. 
  # 7812.5 * .3 = 2343.75 steps. 
  # 7812.5 * .4 = 3125 steps. 
  # 7812.5 * .5 = 3906.25 steps. 

  # if this doesn't work, try on a dummy dataset of 10 examples. 
  weight_decay: 0.01

# Data processing settings
data:
  max_files: 14  # Use all available files (7 python2 + 7 python3)
  tokenize_batch_size: 100  # Optimized based on profiling (was 1000)
  num_proc: 8  # Back to original setting
  data_path_pattern: "olmo-code-balanced/*.jsonl"  # Using balanced data
  # data_path_pattern: "olmo_code_dummy/*.jsonl"

  val_ratio: 0.1  # 10% for validation
  test_ratio: 0.1  # 10% for test

# Loss tracking settings
loss_tracking:
  loss_save_interval: 1  # Print loss every step

# Experiment type
experiment: "py2_py3_special_tokens"

# Special tokens added to tokenizer vocabulary
special_tokens: ["[python2]", "[python3]"]

# Sweep configuration - focused on key hyperparameters
hydra:
  sweeper:
    params:
      training.learning_rate: 4e-6,1e-5,5e-5
      training.weight_decay: 0.01,0.1
      training.warmup_steps: 700,1000